---
title: "Taking Uncertainty Seriously: Bayesian Marginal Structural Models for Causal Inference in Political Science"
bibliography: "../../assets/references.bib"
csl: "../../assets/apsa.csl"
indent: true
output: 
  html_document:
    highlight: breezedark
    css: "../../assets/style.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = '  ',
  fig.path = 'figs/',
  fig.align = "center",
  cache.path = '_cache/',
  fig.process = function(x) {
    x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
    if (file.rename(x, x2))
      x2
    else
      x
  }
)
```

<table class = "author" align="center" style="border-bottom: 2px solid black;">
  <tr>
    <th style="text-align:center;">*Andrew Heiss*</th>
    <th style="text-align:center;">*A. Jordan Nafa*</th>
  </tr>
  <tr>
    <td style="text-align:center; padding-bottom: 16px">Georgia State University</td>
    <td style="text-align:center; padding-bottom: 16px">University of North Texas</td>
  </tr>
</table>


<table style="border-bottom: 2px solid black; font-style: normal;">
<tr>
<td style="text-align:justify;">While the past two decades have been characterized by considerable progress in developing approaches to causal inference in situations where true experimental manipulation is either impractical or impossible, as is the case in much of political science, commonly employed approaches have developed largely within the frameworks of classical econometrics and frequentist non-parametrics [@Blackwell2018]. Unfortunately, these frameworks are limited in their ability to answer many of the questions scholars of international relations and comparative politics are often interested in since they rely heavily upon the assumption of long-run replication rather than quantifying uncertainty directly [@Gill1999; @Gill2020; @Schrodt2014; @Western1994]. In this article we develop a Bayesian approach to the estimation of marginal structural models for causal inference with cross-sectional time series and panel data. We assess the proposed models' performance relative to existing procedures in a simulation study and two empirical examples, demonstrating that our approach performs well in terms of recovering the true parameter values while also lending itself to a more direct and intuitive interpretation. To ensure accessibility, we provide a flexible implementation of the proposed model in the R package `brms` [@Buerkner2017; @Buerkner2018].</td>
</tr>
</table>

## Bayesian Inference in Political Science

Introduced to political science in a series of articles by Bruce Western and Simon Jackman [@Western1994; @Western1998; @Jackman2000; @Jackman2004], Bayesian inference provides several advantages over the frequentist paradigm, particularly for observational research in comparative politics and international relations where the logic of classical inference is often difficult to defend in practice [@Western1994; @Gill1999; @Gill2020; @Schrodt2014]. Paired with significant advances in computational power, the development of efficient Markov Chain Monte Carlo (MCMC) algorithms and user-friendly open-source software packages has made Bayesian inference widely accessible to researchers in the social sciences [@Buerkner2017; @Buerkner2018; @Goodrich2020]. Despite its popularity in the development of measurement models [@Claassen2019; @Claassen2020a; @Clinton2004; @Juhl2018; @Marquardt2018], the application of Bayesian approaches to hypothesis testing remains relatively rare and is generally limited to circumstances where appropriate frequentist models cannot be applied such as in the presence of complete separation in discrete choice models [@Rainey2016; @Gelman2008]. Since some readers may be unfamiliar with the logic and principles of Bayesian methods, this section provides a brief overview of contemporary Bayesian inference and its advantages over the null hypothesis significance testing paradigm that remains dominant in political science.^[It is worth noting here that there is relatively little agreement among statisticians regarding the application of Bayesian estimation and the meaning of the term often varies substantially within and across disciplines. Our definition herein follows that of @Gelman2012 and @McElreath2020 that views priors as assumptions about the universe of plausible effect sizes and emphasizes aggressive model checking as opposed to the philosophical Bayesian view of priors as entirely subjective beliefs.]

## References
